/**
 * 🌟 ASHLEY CENTRALIZED AUTHORITATIVE EMPLOYEES REGISTRY
 * Single source of truth for all Ashley Furniture company staff members.
 * Used uniformly across ERP Web Dashboard, GPS Matrix, Mobile App, and Print views.
 */

import type { Employee } from './types';

export interface AshleyOfficialEmployee extends Employee {
  fullName3Part: string;
  pin: string;
  password?: string;
  startDate: string;
  deviceBound: boolean;
  boundDeviceModel?: string;
  faceRegistered?: boolean;
}

export const ASHLEY_OFFICIAL_EMPLOYEES: AshleyOfficialEmployee[] = [
  {
    id: 'emp-01',
    employeeId: '01',
    name: 'سه هەند مەریوان حەمەسەعید',
    fullName3Part: 'سه هەند مەریوان حەمەسەعید',
    kurdishName: 'سه هەند مەریوان حەمەسەعید',
    role: 'Employee',
    phone: '0770 123 4567',
    email: 'sehend@ashley.com',
    startDate: '2024-01-01',
    employmentStartDate: '2024-01-01',
    pin: '1001',
    password: '1001',
    deviceBound: false,
    isActive: true,
    status: 'active',
    photoUrl: '/employees/emp-01.jpg',
  },
  {
    id: 'emp-02',
    employeeId: '02',
    name: 'دارکۆ حەیدەر حسێن',
    fullName3Part: 'دارکۆ حەیدەر حسێن',
    kurdishName: 'دارکۆ حەیدەر حسێن',
    role: 'Manager',
    phone: '0770 765 4321',
    email: 'darko@ashley.com',
    startDate: '2024-01-01',
    employmentStartDate: '2024-01-01',
    pin: '1002',
    password: '1002',
    deviceBound: true,
    boundDeviceModel: 'iPhone 15 Pro Max',
    faceRegistered: true,
    isActive: true,
    status: 'active',
    photoUrl: '/employees/emp-02.jpg',
  },
  {
    id: 'emp-03',
    employeeId: '03',
    name: 'شادیار هوشیار',
    fullName3Part: 'شادیار هوشیار',
    kurdishName: 'شادیار هوشیار',
    role: 'Employee Supervisor',
    phone: '0750 111 2233',
    email: 'shadyar@ashley.com',
    startDate: '2025-02-01',
    employmentStartDate: '2025-02-01',
    pin: '1003',
    password: '1003',
    deviceBound: false,
    isActive: true,
    status: 'active',
    photoUrl: '/employees/emp-03.jpg',
  },
  {
    id: 'emp-04',
    employeeId: '04',
    name: 'هەڤاڵ حبیب حەمەڕەزا',
    fullName3Part: 'هەڤاڵ حبیب حەمەڕەزا',
    kurdishName: 'هەڤاڵ حبیب حەمەڕەزا',
    role: 'Transport Supervisor',
    phone: '0750 222 3344',
    email: 'heval@ashley.com',
    startDate: '2025-02-15',
    employmentStartDate: '2025-02-15',
    pin: '1004',
    password: '1004',
    deviceBound: false,
    isActive: true,
    status: 'active',
    photoUrl: '/employees/emp-04.jpg',
  },
  {
    id: 'emp-05',
    employeeId: '05',
    name: 'عیماد سەباح نوری',
    fullName3Part: 'عیماد سەباح نوری',
    kurdishName: 'عیماد سەباح نوری',
    role: 'Employee',
    phone: '0770 333 4455',
    email: 'imad@ashley.com',
    startDate: '2023-11-15',
    employmentStartDate: '2023-11-15',
    pin: '1005',
    password: '1005',
    deviceBound: false,
    isActive: true,
    status: 'active',
    photoUrl: '/employees/emp-05.jpg',
  },
  {
    id: 'emp-06',
    employeeId: '06',
    name: 'کامەران عومەر ڕووئوف',
    fullName3Part: 'کامەران عومەر ڕووئوف',
    kurdishName: 'کامەران عومەر ڕووئوف',
    role: 'Employee',
    phone: '0770 444 5566',
    email: 'kameron@ashley.com',
    startDate: '2025-03-10',
    employmentStartDate: '2025-03-10',
    pin: '1006',
    password: '1006',
    deviceBound: false,
    isActive: true,
    status: 'active',
    photoUrl: '/employees/emp-06.jpg',
  },
  {
    id: 'emp-07',
    employeeId: '07',
    name: 'ڕابەر محەمەد مەحمود',
    fullName3Part: 'ڕابەر محەمەد مەحمود',
    kurdishName: 'ڕابەر محەمەد مەحمود',
    role: 'Employee',
    phone: '0770 555 6677',
    email: 'raber@ashley.com',
    startDate: '2024-04-20',
    employmentStartDate: '2024-04-20',
    pin: '1007',
    password: '1007',
    deviceBound: false,
    isActive: true,
    status: 'active',
    photoUrl: '/employees/emp-07.jpg',
  },
  {
    id: 'emp-08',
    employeeId: '08',
    name: 'دانەر محەمەد باسام',
    fullName3Part: 'دانەر محەمەد باسام',
    kurdishName: 'دانەر محەمەد باسام',
    role: 'Employee',
    phone: '0770 666 7788',
    email: 'daner@ashley.com',
    startDate: '2024-05-20',
    employmentStartDate: '2024-05-20',
    pin: '1008',
    password: '1008',
    deviceBound: false,
    isActive: true,
    status: 'active',
    photoUrl: '/employees/emp-08.jpg',
  },
  {
    id: 'emp-09',
    employeeId: '09',
    name: 'ڕێبین سەباح نوری',
    fullName3Part: 'ڕێبین سەباح نوری',
    kurdishName: 'ڕێبین سەباح نوری',
    role: 'Employee',
    phone: '0770 777 8899',
    email: 'rebin@ashley.com',
    startDate: '2024-06-22',
    employmentStartDate: '2024-06-22',
    pin: '1009',
    password: '1009',
    deviceBound: false,
    isActive: true,
    status: 'active',
    photoUrl: '/employees/emp-09.jpg',
  },
  {
    id: 'emp-10',
    employeeId: '10',
    name: 'بەهرەمەند ڕزگار عزیز',
    fullName3Part: 'بەهرەمەند ڕزگار عزیز',
    kurdishName: 'بەهرەمەند ڕزگار عزیز',
    role: 'Employee',
    phone: '0770 888 9900',
    email: 'bahramand@ashley.com',
    startDate: '2025-05-15',
    employmentStartDate: '2025-05-15',
    pin: '1010',
    password: '1010',
    deviceBound: false,
    isActive: true,
    status: 'active',
    photoUrl: '/employees/emp-10.jpg',
  },
  {
    id: 'emp-11',
    employeeId: '11',
    name: 'شادومان یادگار رحیم',
    fullName3Part: 'شادومان یادگار رحیم',
    kurdishName: 'شادومان یادگار رحیم',
    role: 'Employee',
    phone: '0750 999 0011',
    email: 'shaduman@ashley.com',
    startDate: '2024-09-30',
    employmentStartDate: '2024-09-30',
    pin: '1011',
    password: '1011',
    deviceBound: false,
    isActive: true,
    status: 'active',
    photoUrl: '/employees/emp-11.jpg',
  },
  {
    id: 'emp-12',
    employeeId: '12',
    name: 'سەروەت قادر',
    fullName3Part: 'سەروەت قادر',
    kurdishName: 'سەروەت قادر',
    role: 'Employee',
    phone: '0750 000 1122',
    email: 'sarwat@ashley.com',
    startDate: '2025-01-01',
    employmentStartDate: '2025-01-01',
    pin: '1012',
    password: '1012',
    deviceBound: false,
    isActive: true,
    status: 'active',
    photoUrl: '/employees/emp-12.jpg',
  },
  {
    id: 'fe2ad0d3-4d9d-48f8-8cbb-51dc705678e3',
    employeeId: '13',
    name: 'مامۆستا وەلید',
    fullName3Part: 'مامۆستا وەلید ( بەرێوبەر )',
    kurdishName: 'مامۆستا وەلید ( بەرێوبەر )',
    role: 'Super Manager',
    phone: '0770 000 0013',
    email: 'walid@ashley.com',
    startDate: '2024-01-01',
    employmentStartDate: '2024-01-01',
    pin: '1233',
    password: '1233',
    deviceBound: false,
    faceRegistered: false,
    isActive: true,
    status: 'active',
    photoUrl: 'https://picsum.photos/seed/مامۆستا-وەلید/400',
  },
];

export function getOfficialEmployeeById(id: string): AshleyOfficialEmployee | undefined {
  return ASHLEY_OFFICIAL_EMPLOYEES.find(
    (e) => e.id.toLowerCase() === id.toLowerCase() || e.employeeId === id
  );
}

export function getAllOfficialEmployees(): AshleyOfficialEmployee[] {
  return [...ASHLEY_OFFICIAL_EMPLOYEES];
}
