import { Employee, User, Role, AppSettings, AllPdfSettings, PdfSettings, ThemeColors, BranchColors, AnswerOption } from '@/lib/types';
import { adminPermissions, adminAssistantPermissions, viewerPermissions, employeePermissions, financeManagerPermissions, inventoryManagerPermissions, hrManagerPermissions } from '@/lib/permissions';
import en from '@/locales/en.json';
import ku from '@/locales/ku.json';

const defaultAnswers: [AnswerOption, AnswerOption, AnswerOption] = [
    { label: 'Excellent', value: 3 },
    { label: 'Good', value: 2 },
    { label: 'Needs Improvement', value: 1 },
];

const initialRoles: Role[] = [
    { id: 'role-admin', name: 'Admin', permissions: adminPermissions },
    { id: 'role-admin-assistant', name: 'Admin Assistant', permissions: adminAssistantPermissions },
    { id: 'role-finance-manager', name: 'Finance Manager', permissions: financeManagerPermissions },
    { id: 'role-inventory-manager', name: 'Inventory Manager', permissions: inventoryManagerPermissions },
    { id: 'role-hr-manager', name: 'HR Manager', permissions: hrManagerPermissions },
    { id: 'role-viewer', name: 'Viewer', permissions: viewerPermissions },
    { id: 'role-employee', name: 'Employee', permissions: employeePermissions },
];

const initialUsers: User[] = [
    {
        id: 'user-admin-default',
        username: 'admin',
        password: 'password',
        roleId: 'role-admin'
    },
    {
        id: 'user-darko-admin',
        username: 'Darko_admin07',
        password: '123',
        roleId: 'role-admin'
    }
];

const defaultReportColors = {
  general: '#22c55e',
  expense: '#3b82f6',
  overtime: '#f97316',
  bonus: '#8b5cf6',
  withdrawal: '#ef4444'
};

const defaultBranchColors: BranchColors = {
    Erbil: '#f97316',
    Baghdad: '#3b82f6',
    Dohuk: '#8b5cf6',
    Diwan: '#10b981',
};

const defaultReportSettings: PdfSettings = {
    logo: null,
    themeColor: '#22c55e',
    reportColors: defaultReportColors,
    tableTheme: 'striped',
    headerText: '',
    footerText: 'Generated by Ashley DRP System',
    scale: 2,
    width: 800,
    fontSize: 10,
};

const defaultInvoiceSettings: PdfSettings = {
    logo: null,
    themeColor: '#f97316',
    secondaryColor: '#0F172A',
    titleTemplate: 'Transmit to {city}',
    tableTheme: 'grid',
    headerText: 'Ashley DRP',
    footerText: 'Thank you for your business.',
    scale: 2,
    width: 800,
    fontSize: 10,
    branchColors: defaultBranchColors,
};

const defaultCardSettings: PdfSettings = {
    logo: null,
    themeColor: '#8b5cf6',
    headerText: 'Employee ID',
    footerText: 'Official Company ID',
    scale: 3,
    width: 600,
    fontSize: 12,
};

const defaultDatasheetSettings: PdfSettings = {
    logo: null,
    themeColor: '#059669',
    tableTheme: 'grid',
    headerText: 'Product Datasheet',
    footerText: 'Internal Use Only',
    scale: 2,
    width: 800,
    fontSize: 10,
};

const defaultPdfSettings: AllPdfSettings = {
    report: defaultReportSettings,
    invoice: defaultInvoiceSettings,
    card: defaultCardSettings,
    datasheet: defaultDatasheetSettings,
};

const defaultLightColors: ThemeColors = { background: '210 10% 96%', foreground: '0 0% 0%', primary: '220 82% 55%', accent: '220 13% 91%', card: '0 0% 99%', titleBar: '210 10% 94%', tabActiveBackground: '210 10% 98%', tabActiveForeground: '0 0% 0%', tableRowPrimary: '210 10% 96%', tableRowSecondary: '210 10% 94%', huanaHighlight: '210 100% 96%', locationOccupiedBorder: '210 100% 70%', locationOccupiedBg: '210 100% 96%'};
const defaultDarkColors: ThemeColors = { background: '222.2 84% 4.9%', foreground: '210 40% 98%', primary: '217.2 91.2% 59.8%', accent: '217.2 32.6% 17.5%', card: '222.2 84% 4.9%', titleBar: '217.2 91.2% 59.8%', tabActiveBackground: '222.2 84% 4.9%', tabActiveForeground: '210 40% 98%', tableRowPrimary: '222.2 84% 4.9%', tableRowSecondary: '217.2 32.6% 17.5%', huanaHighlight: '217.2 91.2% 15%', locationOccupiedBorder: '217.2 91.2% 50%', locationOccupiedBg: '217.2 91.2% 15%' };


export const initialSettings: AppSettings = {
    appLogo: 'https://logos-world.net/wp-content/uploads/2022/04/Ashley-Emblem.png',
    mainBackground: null,
    loginBackground: 'https://store.ashley.sa/cdn/shop/files/15602_63ed4394-41df-47b4-b450-eff960c05668.jpg?v=1709104619&width=1445',
    loginBackgroundVideo: null,
    loginBackgroundEmbed: 'https://www.youtube.com/embed/wJwZb9PJsNg',
    loginVideoLaptop: 'https://www.youtube.com/embed/wJwZb9PJsNg',
    loginVideoTablet: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    loginVideoPhone: 'https://www.youtube.com/embed/wJwZb9PJsNg',
    loginCardUpperImage: 'https://images2.imgix.net/p4dbimg/p20304/images/ashley-furniture-19202-55-49-amici-linen-loveseat-sofa-sectional_2.jpg?trim=color&trimtol=5&trimcolor=FFFFFF&w=1024&h=768&fm=pjpg&auto=format',
    loginButtonColor: null,
    dashboardBanner: null,
    dashboardBannerHeight: 0,
    newsTickerText: 'Welcome to ASHLEY Do27!',
    fontFamily: 'Inter, system-ui, sans-serif',
    customFont: null,
    printHeaderImage: null,
    printFooterImage: null,
    translations: {
        en: en,
        ku: ku,
    },
    pdfSettings: defaultPdfSettings,
    lightThemeColors: defaultLightColors,
    darkThemeColors: defaultDarkColors,
    salarySettings: {
        overtimeRate: 5000,
        bonusRate: 5000,
    },
    reportHeaderColors: {
        ashleyExpenses: '#3b82f6',
        transmitCargo: '#eab308',
        placementStorage: '#22c55e',
        marketingFeedback: '#06b6d4',
        employees: '#ec4899',
    },
    dashboard: {
      fontSize: 12,
      cardRadius: 12,
      titleColor: '220 82% 55%',
      textColor: '224 71.4% 4.1%',
      accentColor: '220 13% 91%',
      textTransform: 'none',
      activeCardBackground: '',
      activeCardBorder: '',
      buttonColor: '',
      buttonTextColor: '',
    },
    sidebar: {
      fontSize: 12,
      textTransform: 'none',
      activeTabBackground: '',
      activeTabTextColor: '',
      activeTabBorder: '',
    },
    theme: 'light',
    selectedTheme: 'default',
    language: 'en',
    globalTextSize: 14,
    branchTextSize: 9,
    factoryLocation: {
      name: 'کارگەی سەرەکی ئاشڵی (Ashley Factory)',
      lat: 35.5571,
      lng: 45.4352,
      radiusMeters: 500,
    },
};


export const initialData: any = {
    warehouseMaps: [
        {
            id: 'wm-1',
            name: 'Ashley Main Warehouse',
            warehouseType: 'Ashley',
            layoutShape: 'U',
            halls: [
                {
                    id: 'h-1',
                    name: 'Showroom Hall',
                    floors: [
                        {
                            id: 'f-1',
                            name: 'First Floor',
                            zones: [
                                { id: 'z-1', name: 'Premium Sofa Zone', type: 'Zone', itemCount: 45, color: '#3b82f6' },
                                { id: 'z-2', name: 'Bedroom Suite Area', type: 'Zone', itemCount: 12, color: '#10b981' },
                            ]
                        }
                    ]
                },
                {
                    id: 'h-2',
                    name: 'Storage Complex',
                    floors: [
                        {
                            id: 'f-2',
                            name: 'Ground Floor',
                            zones: [
                                { id: 'z-3', name: 'Rack A', type: 'Rack', itemCount: 120, color: '#f59e0b' },
                                { id: 'z-4', name: 'Rack B', type: 'Rack', itemCount: 85, color: '#ef4444' },
                                { id: 'z-5', name: 'Loading Bay', type: 'General', itemCount: 0, color: '#64748b' },
                            ]
                        }
                    ]
                }
            ]
        },
        {
            id: 'wm-huana',
            name: 'Huana Warehouse',
            warehouseType: 'Huana',
            layoutShape: 'I',
            halls: [
                {
                    id: 'h-huana-1',
                    name: 'Huana Main Hall',
                    floors: [
                        {
                            id: 'f-huana-1',
                            name: 'Level 1',
                            zones: [
                                { id: 'z-huana-1', name: 'Rack H1-1-R-01', type: 'Rack', itemCount: 0, color: '#f59e0b', capacity: 50 },
                                { id: 'z-huana-2', name: 'Rack H1-1-R-02', type: 'Rack', itemCount: 0, color: '#f59e0b', capacity: 50 },
                                { id: 'z-huana-3', name: 'Rack H1-1-L-01', type: 'Rack', itemCount: 0, color: '#f59e0b', capacity: 50 },
                                { id: 'z-huana-4', name: 'Rack H1-1-L-02', type: 'Rack', itemCount: 0, color: '#f59e0b', capacity: 50 },
                            ]
                        },
                        {
                            id: 'f-huana-2',
                            name: 'Level 2',
                            zones: [
                                { id: 'z-huana-5', name: 'Rack H1-2-R-01', type: 'Rack', itemCount: 0, color: '#f59e0b', capacity: 50 },
                                { id: 'z-huana-6', name: 'Rack H1-2-R-02', type: 'Rack', itemCount: 0, color: '#f59e0b', capacity: 50 },
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    employees: [
      { id: 'emp-01', name: 'سه هەند مەریوان حەمەسەعید', fullName3Part: 'سه هەند مەریوان حەمەسەعید', employeeId: '01', role: 'Employee', startDate: '2024-01-01', employmentStartDate: '2024-01-01', password: '1001', isActive: true, status: 'active' },
      { id: 'emp-02', name: 'دارکۆ حەیدەر حسێن', fullName3Part: 'دارکۆ حەیدەر حسێن', employeeId: '02', role: 'Manager', startDate: '2025-02-01', employmentStartDate: '2025-02-01', password: '1002', isActive: true, status: 'active' },
      { id: 'emp-03', name: 'شادیار هوشیار', fullName3Part: 'شادیار هوشیار', employeeId: '03', role: 'Employee Supervisor', startDate: '2026-06-01', employmentStartDate: '2026-06-01', password: '1003', isActive: true, status: 'active' },
      { id: 'emp-04', name: 'هەڤاڵ حبیب حەمەڕەزا', fullName3Part: 'هەڤاڵ حبیب حەمەڕەزا', employeeId: '04', role: 'Transport Supervisor', startDate: '2025-05-13', employmentStartDate: '2025-05-13', password: '1004', isActive: true, status: 'active' },
      { id: 'emp-05', name: 'عیماد سەباح نوری', fullName3Part: 'عیماد سەباح نوری', employeeId: '05', role: 'Employee', startDate: '2023-11-15', employmentStartDate: '2023-11-15', password: '1005', isActive: true, status: 'active' },
      { id: 'emp-06', name: 'کامەران عومەر ڕووئوف', fullName3Part: 'کامەران عومەر ڕووئوف', employeeId: '06', role: 'Employee', startDate: '2025-09-15', employmentStartDate: '2025-09-15', password: '1006', isActive: true, status: 'active' },
      { id: 'emp-07', name: 'ڕابەر محەمەد مەحمود', fullName3Part: 'ڕابەر محەمەد مەحمود', employeeId: '07', role: 'Employee', startDate: '2024-04-20', employmentStartDate: '2024-04-20', password: '1007', isActive: true, status: 'active' },
      { id: 'emp-08', name: 'دانەر محەمەد باسام', fullName3Part: 'دانەر محەمەد باسام', employeeId: '08', role: 'Employee', startDate: '2024-05-20', employmentStartDate: '2024-05-20', password: '1008', isActive: true, status: 'active' },
      { id: 'emp-09', name: 'ڕێبین سەباح نوری', fullName3Part: 'ڕێبین سەباح نوری', employeeId: '09', role: 'Employee', startDate: '2024-06-22', employmentStartDate: '2024-06-22', password: '1009', isActive: true, status: 'active' },
      { id: 'emp-10', name: 'بەهرەمەند ڕزگار عزیز', fullName3Part: 'بەهرەمەند ڕزگار عزیز', employeeId: '10', role: 'Employee', startDate: '2026-12-27', employmentStartDate: '2026-12-27', password: '1010', isActive: true, status: 'active' },
      { id: 'emp-11', name: 'شادومان یادگار رحیم', fullName3Part: 'شادومان یادگار رحیم', employeeId: '11', role: 'Employee', startDate: '2024-09-30', employmentStartDate: '2024-09-30', password: '1011', isActive: true, status: 'active' },
    ],
    attendanceLogs: [
      { id: 'att-01', employeeId: 'emp-02', name: 'دارکۆ حەیدەر حسێن', type: 'هاتن (Check In)', time: '2026-08-13 08:25:10', distance: 'داخل کۆمپانیا (12m)', status: 'verified', createdAt: '2026-08-13 08:25:10' },
      { id: 'att-02', employeeId: 'emp-05', name: 'عیماد سەباح نوری', type: 'هاتن (Check In)', time: '2026-08-13 08:30:00', distance: 'داخل کۆمپانیا (18m)', status: 'verified', createdAt: '2026-08-13 08:30:00' },
      { id: 'att-03', employeeId: 'emp-01', name: 'سه هەند مەریوان حەمەسەعید', type: 'هاتن (Check In)', time: '2026-08-13 08:15:00', distance: 'داخل کۆمپانیا (5m)', status: 'verified', createdAt: '2026-08-13 08:15:00' },
      { id: 'att-04', employeeId: 'emp-02', name: 'دارکۆ حەیدەر حسێن', type: 'دەرچوون (Check Out)', time: '2026-08-13 16:30:00', distance: 'داخل کۆمپانیا (12m)', status: 'verified', createdAt: '2026-08-13 16:30:00' },
      { id: 'att-05', employeeId: 'emp-05', name: 'عیماد سەباح نوری', type: 'دەرچوون (Check Out)', time: '2026-08-13 16:35:00', distance: 'داخل کۆمپانیا (18m)', status: 'verified', createdAt: '2026-08-13 16:35:00' },
    ],
    excelFiles: [],
    items: [],
    locations: [],
    expenses: [],
    expenseReports: [],
    overtime: [],
    bonuses: [],
    withdrawals: [],
    itemCategories: [
        { id: 'cat-1', name: 'Sofas' },
        { id: 'cat-2', name: 'Tables' },
        { id: 'cat-3', name: 'Chairs' },
        { id: 'cat-4', name: 'Beds' },
    ],
    transfers: [],
    transferItems: [],
    orderRequests: [],
    marketingFeedbacks: [],
    evaluationQuestions: [
        { id: 'q1', text: 'Commitment to work', answers: defaultAnswers },
        { id: 'q2', text: 'Adherence to working hours', answers: defaultAnswers },
        { id: 'q3', text: 'Acceptance of responsibility', answers: defaultAnswers },
        { id: 'q4', text: 'Initiative and offering suggestions', answers: defaultAnswers },
        { id: 'q5', text: 'Relationship with colleagues', answers: defaultAnswers },
        { id: 'q6', text: 'Appearance and personal hygiene', answers: defaultAnswers },
        { id: 'q7', text: 'Speed of completion', answers: defaultAnswers },
        { id: 'q8', text: 'Work accuracy', answers: defaultAnswers },
        { id: 'q9', text: 'Learning speed', answers: defaultAnswers },
        { id: 'q10', text: 'Problem-solving ability', answers: defaultAnswers },
        { id: 'q11', text: 'Commitment to management directives', answers: defaultAnswers },
        { id: 'q12', text: 'Ability to work under pressure', answers: defaultAnswers },
        { id: 'q13', text: 'Trustworthiness', answers: defaultAnswers },
        { id: 'q14', text: 'Customer service', answers: defaultAnswers },
        { id: 'q15', text: 'Teamwork spirit', answers: defaultAnswers },
        { id: 'q16', text: 'Continuous development', answers: defaultAnswers },
        { id: 'q17', text: 'Marketing Skills', answers: defaultAnswers },
        { id: 'q18', text: 'Sales Performance', answers: defaultAnswers },
    ],
    users: initialUsers,
    roles: initialRoles,
    soldItemsLists: [],
    activityLogs: [],
};
